# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  username: postgres
  password: 1234
  timeout: 5000

development:
  <<: *default
  database: portfolio_development

test: &test
  <<: *default
  database: portfolio_test

production:
  <<: *default
  database: portfolio_development